baseURL = "https://shavenking.me/"
languageCode = "zh-tw"
author = "SHAVENKING"
title = "SHAVENKING"
theme = "black-and-light"
googleAnalytics = "UA-115402930-1"

[params]
  sitename = "SHAVENKING"

[[menu.main]]
    name = "HOME"
    url  = "/"

[[menu.main]]
    name = "RESUME"
    url  = "/resume"
